---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: demo-onlinestore-service

outputs:
- name: currentapp

run:
  path: demo-onlinestore-service/ci/tasks/get-currentapp.sh