---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine    
inputs:
  - name: emo-onlinestore-service

run:
  path: demo-onlinestore-service/ci/tasks/unit.sh