---
resources:
  - name: demo-onlinestore-service
    type: git
    source:
      uri: {{github-uri}}
      branch: {{github-branch}}
    check_every: 10s # for demo

  - name: google-drive
    type: docker-image
    source:
      repository: jpatel4pivotal/google-drive-concourse-resource

jobs:
  - name: unit-test
    public: true
    plan:
      - get: demo-onlinestore-service
        trigger: true
      - task: unit
        file: demo-onlinestore-service/ci/tasks/unit.yml

  - name: build-artifact
    public: true
    plan:
      - get: demo-onlinestore-service
        trigger: true
        passed: [ unit-test ]
      - task: build
        file: demo-onlinestore-service/ci/tasks/build.yml
      - put: google-drive
        params: { file: build/pcf-demo-*.war }